Consolidate maintenance by the Team of technical reports
w3c/w3process pull request #860
Opened 2024-04-30 07:03 UTC by frivoal

Merge into a single section all clauses about the Team maintaining technical reports in the absence of a chartered  group, and uniformize the types of edits that they can make (class 1 changes, errata, and Team corrections).

See https://github.com/w3c/w3process/issues/120

2024-04-30 07:12 UTC, frivoal commented
Reasoning for being a little stricter here than in the normal definition of [class 2 changes](https://www.w3.org/2023/Process-20231103/#class-2): normally, if anybody, and in particular any member of the working group, disagrees that a change is class 2, then it isn't; you cannot publish it as class 2, and need to go through whatever hoops are needed for class 3 changes in your particular type of document.

However, here, because there's not Working Group, there isn't really anyone who has a pre-publication chance to say "wait a minute, that's not editorial". Because of that, the Team needs to be more conservative than others as to what class 2 changes it can make.

We could also ban class 2 changes other than errata and candidate amendments, but that would prevent the Team from fixing typos, spelling mistakes, affiliation or name changes… That seems stricter than necessary. Hence the middle ground attempted by this PR.

2024-04-30 14:50 UTC, TallTed requested changes
Just a missing comma

2024-04-30 14:50 UTC, TallTed commented on index.bs
> +	(i.e. they are not covered by the Patent Policy).
```suggestion
	(i.e., they are not covered by the Patent Policy).
```

2024-05-08 14:33 UTC, fantasai approved these changes

2024-05-08 17:19 UTC, merged