[Editorial] Give context for candidate amendments when revising a REC
w3c/w3process pull request #862
Opened 2024-05-01 04:58 UTC by frivoal

This change gives a little bit more context about how to make normative changes to a REC. Technically, and this is what the existing text talked about, they are made by folding in candidate amendments. However, someone just reading that section may not be aware of what candidate amendments are and how they are made to begin with.

This gives just a little bit of context to help people piece things together.

This is a small step towards addressing https://github.com/w3c/w3process/issues/700

2024-05-01 14:46 UTC, TallTed requested changes
minor grammar

2024-05-01 14:46 UTC, TallTed commented on index.bs
> +	the technical and editorial soundness.
```suggestion
	its technical and editorial soundness.
```

2024-05-01 14:46 UTC, TallTed commented on index.bs
> +	They are therefore be published following the provisions of [[#revised-rec-editorial]].
```suggestion
	They are therefore published following the provisions of [[#revised-rec-editorial]].
```

2024-05-01 14:46 UTC, TallTed commented on index.bs
> +	They are therefore be published following the provisions of [[#revised-rec-editorial]].
```suggestion
	They are therefore published following the provisions of [[#revised-rec-editorial]].
```

2024-05-08 14:28 UTC, fantasai approved these changes

2024-05-08 15:04 UTC, merged