Synchronize Advisory Committee representative and Consortium Member Representative
w3c/w3process pull request #937
Opened 2024-10-25 02:35 UTC by frivoal

See https://github.com/w3c/AB-memberonly/issues/247

2024-11-08 11:59 UTC, Heathoney approved these changes

2024-11-27 08:23 UTC, NameNoQuality approved these changes

2024-11-27 08:23 UTC, NameNoQuality commented on index.bs
> +	When a [=Member Association=] joins W3C,
#912

2024-11-27 08:26 UTC, NameNoQuality approved these changes

2024-11-27 08:26 UTC, NameNoQuality commented on index.bs
> +	When a [=Member Association=] joins W3C,
@aungko.use@gmail.com

2025-01-08 09:04 UTC, preechapon-cmd approved these changes

2025-01-16 02:39 UTC, tantek approved these changes
This seems like a reasonable step forward.

I'd request that the editor consider the impact of these changes on the "alternate representative" role to make sure that role still works as expected/desired. I trust the editor's judgment on this interaction.

2025-07-04 08:15 UTC, frivoal commented
The proposed text has mentions member associations, and therefore has a dependency on https://github.com/w3c/board/issues/249

2025-07-07 16:11 UTC, TallTed requested changes
Language tweaks for clarity.

2025-07-07 16:11 UTC, TallTed commented on index.bs
> +	each W3C [=Member=] organization that is not a [=Member Association=] (known as a “<i>Consortium Member</i>” in the Bylaws)
The existing parenthetical structure makes it seem that _a `Member Association` is known as a `Consortium Member` in the Bylaws_, rather than _a W3C Member organization that is not a `Member Association` is known as a `Consortium Member` in the Bylaws_.
```suggestion
	each “<i>Consortium Member</i>” (that is, each W3C [=Member=] organization that is not a [=Member Association=])
```

2025-07-07 16:11 UTC, TallTed commented on index.bs
> +	For the purposes of the W3C Process,
```suggestion
	For purposes of the W3C Process,
```

2025-07-07 16:11 UTC, TallTed commented on index.bs
> +	each W3C [=Member=] organization that is not a [=Member Association=] (known as a “<i>Consortium Member</i>” in the Bylaws)
or
```suggestion
	each W3C [=Member=] organization that is not a [=Member Association=] (that is, each organization the Bylaws would refer to as a “<i>Consortium Member</i>”)
```

2025-07-08 00:00 UTC, frivoal commented on index.bs
> +	each W3C [=Member=] organization that is not a [=Member Association=] (known as a “<i>Consortium Member</i>” in the Bylaws)
Good catch. I think I lean towards your first suggestion, but both seam reasonable to me. Any other opinions?

2025-07-15 06:40 UTC, tantek approved these changes
Looks good with either of the suggested fixes by @TallTed.

2025-09-26 13:58 UTC, TallTed approved these changes

2025-09-26 22:24 UTC, tantek approved these changes

2026-01-20 09:50 UTC, frivoal commented
This PR is still a work-in-progress, and it is neither certain that we will decide to do this, nor that these are the exact right words for doing it. But in the spirit of trying to see what it would look like if we did, I have made an additional commit (https://github.com/w3c/process/pull/937/commits/4634789e8cfe00084c1b7f4bc9046576a29362ee) to reduce the coupling with the bylaws.

The Process only needs to concern itself with the fact that the bylaws define that Consortium Members have Consortium Member Representatives, and that some Members (in the sense of the Process) do not qualify to be Consortium Members (and thus don't have a C.M.Rep.). It does not need to concern itself with why the bylaws exclude some organizations from being Consortium Members, and therefore reducing the interdependence is desirable: this allows the bylaws to evolve the criteria if needed (including possibly to address https://github.com/w3c/board/issues/249), without needing any revision in the Process.

I also made a minor edit, in response to @tantek in https://github.com/w3c/process/pull/937#pullrequestreview-2554594801, to clarify what that means for the alternate AC Rep.

2026-06-11 14:14 UTC, hober approved these changes

2026-06-23 21:32 UTC, brentzundel approved these changes

2026-06-24 14:48 UTC, merged